---
# Install Adminer theme
- name: Download adminer flat theme
  get_url:
    url: https://raw.githubusercontent.com/vrana/adminer/master/designs/{{ adminer_theme }}/adminer.css
    dest: "{{ adminer_install_dir }}"
    mode: 0644

- name: Symlink Adminer theme into configured directories.
  file:
    src: "{{ adminer_install_dir }}/adminer.css"
    dest: "{{ item }}/adminer.css"
    state: link
  with_items: "{{ adminer_symlink_dirs }}"