---
- name: Web server installation
  hosts: web
  remote_user: root
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - franklinkim.git
    - franklinkim.users-oh-my-zsh
    - mtpereira.passenger
    - rvm_io.rvm1-ruby
    - nbz4live.php-fpm
    - novuso.php-cli
    - tersmitten.composer
    - mjanser.mysql
    - mjanser.phpmyadmin
    - hashbangcode.imagemagick
    - franklinkim.htpasswd
    - williamyeh.nodejs
    # - avconv
    - tools
    - misc
...