---
- name: Web server installation
  hosts: web
  remote_user: root
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - utils
    - franklinkim.git

    #
    # Users and ZSH
    # ===============
    - franklinkim.sudo
    - franklinkim.users-oh-my-zsh

    #
    # Servers
    # =========
    - geerlingguy.nginx # Nginx

    #
    # RVM and Ruby
    # ==============
    - role: rvm_io.ruby
      become_user: '{{ user }}'

    #
    # PHP fpm
    # =========
    - mjanser.php
    - tersmitten.composer

    #
    # Databases
    # ===========
    - mysql-db-import # Copy local databases to remote folder
    - mjanser.mysql
    - role: mjanser.phpmyadmin
      when: database_management == 'phpmyadmin'
    - role: geerlingguy.adminer
      when: database_management == 'adminer'

    #
    # NodeJS
    # ========
    - williamyeh.nodejs

    #
    # Convert packages
    # ==================
    - hashbangcode.imagemagick
    - avconv

    #
    # Postfix [Mail server]
    # =======================
    - Stouts.postfix

    #
    # Cache
    # =======
    - geerlingguy.memcached
    # - geerlingguy.redis

    #
    # Timezone and locale
    # =====================
    - franklinkim.timezone
    - franklinkim.environment

    #
    # Security
    # ==========
    # - letsencrypt
    - franklinkim.htpasswd
    - franklinkim.ufw
    - franklinkim.fail2ban
    # - proftpd
    - security
    - lr-agenceweb.backup-manager # Backup and save

    #
    # Fixes
    # =======
    - zsh-fix
    - nanorc-fix
    - git-fix
    - nginx-fix
    - gems-fix
    - php-fix
    - mysql-fix
    - fail2ban-fix
