---
- name: Web server installation
  hosts: web
  remote_user: root
  become: yes

  roles:
    - franklinkim.git
    - franklinkim.users-oh-my-zsh
    - mtpereira.passenger
    - rvm_io.rvm1-ruby
    - nbz4live.php-fpm
    - novuso.php-cli
    - tersmitten.composer
    - mjanser.mysql
    - mjanser.phpmyadmin
    - hashbangcode.imagemagick
    - franklinkim.htpasswd
    # - avconv
    - tools
    - misc

  vars:
    # Default
    user: vagrant
    user_home_directory: '/home/{{ user }}'

    # ZSH
    users:
      - username: '{{ user }}'
        name: '{{ user }}'
        authorized_keys: []
        oh_my_zsh:
          theme: agnoster
          plugins: git zsh-syntax-highlighting

    # Passenger
    passenger_webserver: nginx

    # RVM and Ruby
    rvm1_rvm_version: 'stable'
    rvm1_rvm_check_for_updates: True
    rvm1_install_path: '/home/{{ ansible_ssh_user }}/.rvm'
    rvm1_rubies:
      - 'ruby-2.3.0'

    # PHP FPM
    php_fpm_socket: /var/run/php5-fpm.sock
    php_fpm_pools:
     - name: www
       listen.owner: www-data
       listen.group: www-data
       listen.mode: '0660'
       user: www-data
       group: www-data
       listen: '{{ php_fpm_socket }}'
       chdir: /

    # MySQL
    mysql_root_password: root
    mysql_databases:
      - name: ansible_demo
        import_file: ~
    mysql_users:
      - name: ansible
        password: ansible
        privileges: "ansible_demo.*:ALL"

    # PhpMyAdmin
    phpmyadmin_server_host: localhost
    phpmyadmin_server_auth_type: config
    phpmyadmin_php_fpm_socket: 'unix:{{ php_fpm_socket }}'
...