---
- name: Web server installation
  hosts: web
  remote_user: root
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - utils
    - franklinkim.git

    # Users
    - franklinkim.sudo
    - franklinkim.users-oh-my-zsh

    # Nginx + Passenger
    - mtpereira.passenger
    - franklinkim.htpasswd
    - letsencrypt

    # Ruby
    - role: rvm_io.rvm1-ruby
      become_user: '{{ user }}'

    # PHP
    - nbz4live.php-fpm
    - novuso.php-cli
    - tersmitten.composer

    # Databases
    - mjanser.mysql
    - role: mjanser.phpmyadmin
      when: install_phpmyadmin

    - role: geerlingguy.adminer
      when: install_adminer
    - role: adminer-theme
      when: install_adminer

    # NodeJS
    - williamyeh.nodejs

    # Convert packages
    - hashbangcode.imagemagick
    - avconv

    # Cache
    - geerlingguy.memcached

    # Timezone and locale
    - franklinkim.timezone
    - franklinkim.environment

    # Security
    - franklinkim.ufw
    - franklinkim.fail2ban
    - proftpd
    - security

    # Backup and save
    - lr-agenceweb.backup-manager

    # Fix
    - git-fix
    - zsh-fix
    - nginx-fix
    - nanorc-fix
    - gems-fix
    - php-fix
    - fail2ban-fix
