---
- name: Web server installation
  hosts: web
  remote_user: root
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - franklinkim.git

    # Users
    - franklinkim.sudo
    - franklinkim.users-oh-my-zsh

    # Nginx + Passenger
    - mtpereira.passenger

    # Ruby
    - role: rvm_io.rvm1-ruby
      become_user: '{{ user }}'

    # PHP
    - nbz4live.php-fpm
    - novuso.php-cli
    - tersmitten.composer

    # MySQL
    - mjanser.mysql
    - mjanser.phpmyadmin

    # NodeJS
    - williamyeh.nodejs

    # Libraries
    - hashbangcode.imagemagick
    # - avconv

    # Misc
    - franklinkim.htpasswd
    - tools
    - misc
...