---
- name: Web server installation
  hosts: web
  remote_user: root
  become: yes
  vars_files:
    - vars/main.yml

  roles:
    - tools
    - franklinkim.git

    # Users
    - franklinkim.sudo
    - franklinkim.users-oh-my-zsh

    # Nginx + Passenger
    - mtpereira.passenger
    - letsencrypt

    # Ruby
    - role: rvm_io.rvm1-ruby
      become_user: '{{ user }}'

    # PHP
    - nbz4live.php-fpm
    - novuso.php-cli
    - tersmitten.composer

    # MySQL
    - mjanser.mysql
    - mjanser.phpmyadmin

    # NodeJS
    - williamyeh.nodejs

    # Convert packages
    - hashbangcode.imagemagick
    # - avconv

    # Cache
    - geerlingguy.memcached

    # Timezone and locale
    - franklinkim.timezone
    - franklinkim.environment

    # Backup and save
    - elao.backup-manager

    # Fix
    - zsh-fix
    - nginx-fix
    - nanorc-fix
    - gems-fix

    # Misc
    - franklinkim.htpasswd
    - misc
...