- src: franklinkim.git
- src: franklinkim.sudo
- src: franklinkim.users-oh-my-zsh
- src: mtpereira.passenger
- src: rvm_io.rvm1-ruby
- src: nbz4live.php-fpm
- src: novuso.php-cli
- src: tersmitten.composer
- src: mjanser.mysql
- src: mjanser.phpmyadmin
- src: geerlingguy.adminer
- src: williamyeh.nodejs
- src: hashbangcode.imagemagick
- src: geerlingguy.memcached
- src: franklinkim.timezone
- src: franklinkim.environment
- src: franklinkim.htpasswd
- src: franklinkim.ufw
- src: franklinkim.fail2ban

- name: elao.backup-manager
  src: https://github.com/ElaoInfra/ansible-role-backup-manager
  version: '1.0'