---
- name: clone zsh syntax highlighting plugin
  git: >
    repo=https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest={{ user_home_directory }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Add ll alias showing dotfiles to .zshrc
  lineinfile:
    dest: /home/{{ user }}/.zshrc
    regexp: ^ll=
    line: "\nalias ll='ls -ahlF'"
