---
- name: clone zsh syntax highlighting plugin
  git: >
    repo=https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest={{ user_home_directory }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

- name: Add ll alias showing dotfiles to .zshrc
  lineinfile:
    dest: '{{ user_home_directory }}/.zshrc'
    line: "alias ll='ls -ahlF'"

- name: Add cll alias for coloring tail logs
  lineinfile:
    dest: '{{ user_home_directory }}/.zshrc'
    line: "alias cll='source-highlight -f esc -s log'"
