---
- name: Upload conf file syntax highlighting for nano
  template:
    src: templates/conf.nanorc
    dest: /usr/share/nano/conf.nanorc
    force: no

- name: Upload yml file syntax highlighting for nano
  template:
    src: templates/yml.nanorc
    dest: /usr/share/nano/yml.nanorc
    force: no

- name: Upload slim file syntax highlighting for nano
  template:
    src: templates/slim.nanorc
    dest: /usr/share/nano/slim.nanorc
    force: yes

- name: Add colorization for conf file with nano editor
  blockinfile:
    dest: /etc/nanorc
    block: |
      ## Configuration files (catch-all syntax)
      include "/usr/share/nano/conf.nanorc"
      include "/usr/share/nano/yml.nanorc"
      include "/usr/share/nano/slim.nanorc"
    force: no

- name: Enable autoindent option
  replace:
    dest: /etc/nanorc
    regexp: '# set autoindent'
    replace: "set autoindent"

- name: Show line numbers
  replace:
    dest: /etc/nanorc
    regexp: '# set const'
    replace: "set const"
