---
# Replace default root_path for nginx
- name:
  replace:
    dest: /etc/nginx/sites-available/default
    regexp: '/var/www/html'
    replace: '/usr/share/nginx/html'
  notify: nginx restart

# Replace default Nginx homepage by custom one
- name: Upload new Nginx homepage
  template:
    src: 'templates/{{ nginx_custom_root_template }}.html'
    dest: '/usr/share/nginx/html/index.html'
    force: yes
  when: nginx_use_custom_root_html and nginx_custom_root_template != ''
  notify: nginx restart

# PHP FPM
- name: Activate PHP FPM for default vhost
  blockinfile:
    dest: /etc/nginx/sites-available/default
    insertbefore: "# deny access to .htaccess files"
    block: |
      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:{{ fpm_listen }};
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
      }
  notify: nginx restart

- name: Add index.php as primary index file to check
  replace:
    dest: /etc/nginx/sites-available/default
    regexp: 'index index.html'
    replace: 'index index.php index.html'
  notify: nginx restart

# PHPMyAdmin
- name: Include PHPMyAdmin location to default nginx vhost
  lineinfile:
    dest: /etc/nginx/sites-available/default
    insertbefore: "# pass the PHP scripts"
    line: "\tinclude /etc/nginx/global.d/phpmyadmin.conf;"
  notify: nginx restart
  when: database_management == 'phpmyadmin'
