---
- name: Include PHPMyAdmin location to default nginx vhost
  lineinfile:
    dest: /etc/nginx/sites-available/default
    insertbefore: "# pass the PHP scripts"
    line: "\t# include PHPMyAdmin location\n \tinclude /etc/nginx/global.d/phpmyadmin.conf;\n"
  notify: nginx restart
