---
- name: Upload slack notifier
  template:
    src: templates/slack-notify.conf.j2
    dest: /etc/fail2ban/action.d/slack-notify.conf
    force: no
    owner: root
    group: root
    mode: 0640
  when: fail2ban_fix.slack_notifier
  notify: restart fail2ban
