---
- name: Installation of various tools
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - htop
    - unzip
    - pydf
    - source-highlight # colorize tail logs
    - tree # list folders as tree
    - libmysqlclient-dev # for mysql
    - libpq-dev # for postgresql
    - libgmp-dev # to install gems without errors
    - wkhtmltopdf # HTML to PDF
