---
- name: Installation of various tools
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - htop
    - unzip
    - pydf
    - libmysqlclient-dev # for mysql
    - libpq-dev # for postgresql
    - libgmp-dev # to install gems without errors