---
- name: Create .gemrc file with --no-rdoc and --no-ri options
  template:
    src: templates/.gemrc
    dest: '{{ user_home_directory }}'
    owner: '{{ user }}'
    group: '{{ user }}'

# - name: Install usefull gems
#   gem: name={{ item }} state=latest
#   with_items:
#     - backup # Databases export
